//! Code-generation printing helpers for the `fuga` binary.
//!
//! Extracted from `src/main.rs` during monolith decomposition
//! (Phase 1 of docs/refactor-plan.md). Self-contained: emit
//! Rust/C++ scaffolding text via println!.

/// True if a token looks like a real identifier (not a digit run).
pub fn is_name_token(tok: &str) -> bool {
    let t = tok.trim_matches('▁');
    t.len() >= 3
        && t.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !t.chars().all(|c| c.is_ascii_digit())
}

/// Capitalize the first char of `s`; fall back to "Phase".
pub fn capitalize(s: &str) -> String {
    let t = s.trim_start_matches('▁');
    let mut c = t.chars();
    match c.next() {
        Some(f) => f.to_uppercase().chain(c).collect(),
        None => "Phase".to_string(),
    }
}

/// Emit a Rust struct scaffold (resonance-driven codegen).
pub fn print_rust_code(
    name: String,
    dim: usize,
    k: usize,
    features: &[&str],
    experts: &[u32],
    layers: &[u32],
) {
    let mut fields = String::new();
    let mut methods = String::new();
    for f in features {
        match *f {
            "attention" => {
                fields.push_str("    /// Resonance-driven: scaled dot-product attention.\n    pub attention_scale: f32,\n");
                methods.push_str("    pub fn attention(&self, q: &[f32], k: &[f32]) -> f32 {\n        let s: f32 = q.iter().zip(k.iter()).map(|(a, b)| a * b).sum();\n        s * self.attention_scale\n    }\n\n");
            }
            "gate" => {
                fields.push_str("    /// Resonance-driven: gated activation weight.\n    pub gate_weight: f32,\n");
                methods
                    .push_str("    pub fn gate(&self, x: f32) -> f32 { x * self.gate_weight }\n\n");
            }
            "norm" => {
                fields.push_str("    /// Resonance-driven: layer-normalization epsilon.\n    pub norm_eps: f32,\n");
                methods.push_str("    pub fn normalize(&self, x: &[f32]) -> f32 {\n        let mean = x.iter().sum::<f32>() / x.len() as f32;\n        let var = x.iter().map(|v| (v - mean) * (v - mean)).sum::<f32>() / x.len() as f32;\n        (x[0] - mean) / (var + self.norm_eps).sqrt()\n    }\n\n");
            }
            "router" => {
                fields.push_str("    /// Resonance-driven: top-k MoE router threshold.\n    pub route_cap: u16,\n");
                methods
                    .push_str("    pub fn route(&self, score: f32) -> bool { score > 0.35 }\n\n");
            }
            "embed" | "token" => {
                fields.push_str(
                    "    /// Resonance-driven: embedding dimension.\n    pub embed_dim: usize,\n",
                );
                methods.push_str("    pub fn embed(&self, token: u32) -> u32 { token % self.embed_dim as u32 }\n\n");
            }
            _ => {
                fields.push_str(&format!(
                    "    /// Resonance-driven field: {}.\n    pub {}_gain: f32,\n",
                    f, f
                ));
                methods.push_str(&format!(
                    "    pub fn {}_step(&self, x: f32) -> f32 {{ x * self.{}_gain }}\n\n",
                    f, f
                ));
            }
        }
    }
    if fields.is_empty() {
        fields.push_str("    /// Resonance-driven: model dimension.\n    pub dim: usize,\n");
        methods.push_str("    pub fn forward(&self, x: &[f32]) -> f32 { x.iter().sum::<f32>() / x.len() as f32 }\n\n");
    }

    println!("// Generated by `fuga codegen` — resonance-driven scaffolding.\n");
    println!("pub const MODEL_DIM: usize = {};", dim);
    println!("pub const TOP_K: usize = {};", k.max(1));
    if !experts.is_empty() {
        println!(
            "pub const EXPERT_IDS: [u32; {}] = {:?};",
            experts.len(),
            experts
        );
    }
    if !layers.is_empty() {
        println!(
            "pub const LAYER_IDS: [u32; {}] = {:?};",
            layers.len(),
            layers
        );
    }
    println!();
    println!("pub struct {} {{", name);
    println!("{}", fields.trim_end_matches('\n'));
    println!("}}\n");
    println!("impl {} {{", name);
    println!("    pub fn new(dim: usize) -> Self {{");
    println!("        Self {{");
    for f in features {
        match *f {
            "attention" => println!("            attention_scale: 0.7071,"),
            "gate" => println!("            gate_weight: 1.0,"),
            "norm" => println!("            norm_eps: 1e-5,"),
            "router" => println!("            route_cap: 1024,"),
            "embed" | "token" => println!("            embed_dim: dim,"),
            _ => println!("            {}_gain: 1.0,", f),
        }
    }
    if features.is_empty() {
        println!("            dim,");
    }
    println!("        }}");
    println!("    }}\n");
    println!("{}", methods.trim_end_matches('\n'));
    println!("}}\n");
}

/// Emit a C++ struct scaffold (resonance-driven codegen).
pub fn print_cpp_code(
    name: String,
    dim: usize,
    k: usize,
    features: &[&str],
    experts: &[u32],
    layers: &[u32],
) {
    println!("// Generated by `fuga codegen` — resonance-driven scaffolding.\n");
    println!("#pragma once");
    println!("#include <vector>\n");
    println!("namespace phase {{");
    println!("static constexpr std::size_t MODEL_DIM = {};", dim);
    println!("static constexpr int TOP_K = {};", k.max(1));
    if !experts.is_empty() {
        println!(
            "static constexpr int EXPERT_IDS[{}] = {{{}}};",
            experts.len(),
            experts
                .iter()
                .map(|n| n.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    println!();
    println!("struct {} {{", name);
    for f in features {
        match *f {
            "attention" => println!("    float attention_scale{{0.7071f}}; // resonance-driven"),
            "gate" => println!("    float gate_weight{{1.0f}};        // resonance-driven"),
            "norm" => println!("    float norm_eps{{1e-5f}};         // resonance-driven"),
            "router" => println!("    unsigned route_cap{{1024}};      // resonance-driven"),
            "embed" | "token" => println!("    std::size_t embed_dim{{MODEL_DIM}};"),
            _ => println!("    float {}_gain{{1.0f}};", f),
        }
    }
    if features.is_empty() {
        println!("    std::size_t dim{{MODEL_DIM}};");
    }
    println!();
    println!("    float forward(const std::vector<float>& x) const {{");
    if features.contains(&"norm") {
        println!("        float mean = 0.0f;");
        println!("        for (float v : x) mean += v;");
        println!("        mean /= static_cast<float>(x.size());");
        println!("        float var = 0.0f;");
        println!("        for (float v : x) var += (v - mean) * (v - mean);");
        println!("        var /= static_cast<float>(x.size());");
        println!("        return (x[0] - mean) / std::sqrt(var + norm_eps);");
    } else {
        println!("        float acc = 0.0f;");
        println!("        for (float v : x) acc += v;");
        println!("        return acc / static_cast<float>(x.size());");
    }
    println!("    }}");
    println!("}};\n}} // namespace phase\n");
}
