// refactor: optimize expert weight routing and bitwise threshold filtering
// generated by Fuga agent
use crate::weaver::super_token::{SuperToken, TokenRole};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetExpert {
    CodeLogic,
    AgentExecutor,
    SymbolicMath,
    GeneralLanguage,
    MemoryWrite,
}

impl TargetExpert {
    pub fn name(&self) -> &'static str {
        match self {
            TargetExpert::CodeLogic => "code",
            TargetExpert::AgentExecutor => "agent",
            TargetExpert::SymbolicMath => "math",
            TargetExpert::GeneralLanguage => "general",
            TargetExpert::MemoryWrite => "memory",
        }
    }
}

pub struct DynamicRouter;

impl DynamicRouter {
    pub fn route(st: &SuperToken) -> TargetExpert {
        let flags = st.role_flags.bits();

        if flags & TokenRole::CODE_CHUNK.bits() != 0 {
            return TargetExpert::CodeLogic;
        }
        if flags & TokenRole::TOOL_CALL.bits() != 0 {
            return TargetExpert::AgentExecutor;
        }
        if flags & TokenRole::MATH_EXPR.bits() != 0 {
            return TargetExpert::SymbolicMath;
        }
        if flags & TokenRole::MEMORY_UPDATE.bits() != 0 {
            return TargetExpert::MemoryWrite;
        }
        TargetExpert::GeneralLanguage
    }

    pub fn route_by_peek(source: &str) -> TargetExpert {
        let s = source.trim_start();
        if s.starts_with("def ")
            || s.starts_with("fn ")
            || s.starts_with("impl ")
            || s.starts_with("class ")
            || s.starts_with("function ")
            || s.starts_with("const ")
            || s.starts_with("let ")
            || s.starts_with("var ")
            || s.starts_with("import ")
            || s.starts_with("export ")
            || s.starts_with("<")
            || s.starts_with("* ")
            || s.starts_with("@")
            || s.starts_with("<!")
            || s.contains("```")
        {
            return TargetExpert::CodeLogic;
        }
        if s.starts_with("+")
            || s.starts_with("-")
            || s.starts_with("=")
            || s.contains("∑")
            || s.contains("∫")
            || s.chars()
                .any(|c| c == '=' || c == '+' || c == '*' || c == '/' || c == '^')
        {
            return TargetExpert::SymbolicMath;
        }
        if s.contains("tool") || s.contains("agent") || s.contains("call") || s.starts_with("/") {
            return TargetExpert::AgentExecutor;
        }
        TargetExpert::GeneralLanguage
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::hypervector::Hypervector;
    use crate::weaver::super_token::SuperToken;

    #[test]
    fn test_route_code_chunk() {
        let hv = Hypervector::random(1024);
        let mut st = SuperToken::new(hv, 0);
        st.role_flags = TokenRole::CODE_CHUNK;
        assert_eq!(DynamicRouter::route(&st), TargetExpert::CodeLogic);
    }

    #[test]
    fn test_route_tool_call() {
        let hv = Hypervector::random(1024);
        let mut st = SuperToken::new(hv, 0);
        st.role_flags = TokenRole::TOOL_CALL;
        assert_eq!(DynamicRouter::route(&st), TargetExpert::AgentExecutor);
    }

    #[test]
    fn test_route_general_by_default() {
        let hv = Hypervector::random(1024);
        let st = SuperToken::new(hv, 0);
        assert_eq!(DynamicRouter::route(&st), TargetExpert::GeneralLanguage);
    }

    #[test]
    fn test_route_by_peek_code() {
        assert_eq!(
            DynamicRouter::route_by_peek("def foo(x):"),
            TargetExpert::CodeLogic
        );
        assert_eq!(
            DynamicRouter::route_by_peek("fn bar() {"),
            TargetExpert::CodeLogic
        );
    }

    #[test]
    fn test_route_by_peek_general() {
        assert_eq!(
            DynamicRouter::route_by_peek("Hello world"),
            TargetExpert::GeneralLanguage
        );
    }
}

pub struct ExpertConfig {
    pub active_blocks: Vec<TargetExpert>,
    pub activation_threshold: f64,
}

impl Default for ExpertConfig {
    fn default() -> Self {
        Self {
            active_blocks: vec![
                TargetExpert::GeneralLanguage,
                TargetExpert::CodeLogic,
                TargetExpert::SymbolicMath,
                TargetExpert::AgentExecutor,
            ],
            activation_threshold: 0.5,
        }
    }
}
